<a href="https://colab.research.google.com/github/AliciaWang55/Machine-Learning-in-Predictive-Cardiology/blob/main/knn_input_alicia_finalproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score
from sklearn.metrics import confusion_matrix
from tensorflow.keras import layers, models
from sklearn.preprocessing import StandardScaler

! gdown 1uHmHZdG4shgl3UwB1jtvkgmrQz9Zuwp8

Downloading...
From: https://drive.google.com/uc?id=1uHmHZdG4shgl3UwB1jtvkgmrQz9Zuwp8
To: /content/heart_data.csv
100% 3.35M/3.35M [00:00<00:00, 50.5MB/s]

In [ ]:
df = pd.read_csv('heart_data.csv')
df.head()

,index,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [ ]:
df['active'] = 1-df['active']
df.head()

,index,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,0,18393,2,168,62.0,110,80,1,1,0,0,0,0
1,1,1,20228,1,156,85.0,140,90,3,1,0,0,0,1
2,2,2,18857,1,165,64.0,130,70,3,1,0,0,1,1
3,3,3,17623,2,169,82.0,150,100,1,1,0,0,0,1
4,4,4,17474,1,156,56.0,100,60,1,1,0,0,1,0

In [ ]:
# X = df[['age', 'gender', 'height', 'weight', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active']] #67%
#X = df[['age', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active']] #70% / 25: 70.19% / gender, height, and weight aren't that important
#X = df[['age', 'ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco']] # 69% / 77: 69.3%  / active is important
# X = df[['ap_hi', 'ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active']] # 72% / age is not important
#X = df[['ap_lo', 'cholesterol', 'gluc', 'smoke', 'alco', 'active']] # 69% / ap_hi is important
X = df[['ap_hi', 'cholesterol', 'gluc', 'smoke', 'alco', 'active']] # 73% / ap_lo not that important / 0.726214 at several including 88
#X = df[['gender', 'ap_hi', 'cholesterol', 'gluc', 'smoke', 'alco', 'active']] # 72% / gender not important
#X = df[['ap_hi', 'cholesterol', 'gluc', 'smoke', 'active']] # 73 again without alco
#X = df[['ap_hi', 'gluc', 'smoke', 'active']] # 71 / cholesterol is important

#CNN: 7x1x1 first conv layer 3x1 or 3x1

y = df['cardio']
# X = X.to_numpy()
# y = y.to_numpy()
print(X.shape)

(70000, 6)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42) # took a pic of 17, 42 is higher

for i in range(1,100):
  model_knn = KNeighborsClassifier(n_neighbors=i, weights='distance')
  model_knn.fit(X_train, y_train)
  score = model_knn.score(X_test, y_test)
  print(i, score)


from sklearn.metrics import classification_report

y_pred_knn = model_knn.predict(X_test)

print(classification_report(y_test, y_pred_knn))

1 0.5967857142857143
2 0.5951428571428572
3 0.6162142857142857
4 0.599
5 0.6193571428571428
6 0.6145714285714285
7 0.6119285714285714
8 0.7108571428571429
9 0.7161428571428572
10 0.714
11 0.7216428571428571
12 0.7231428571428572
13 0.7225
14 0.7221428571428572
15 0.7220714285714286
16 0.7220714285714286
17 0.6252142857142857
18 0.6282142857142857
19 0.6280714285714286
20 0.7223571428571428
21 0.7230714285714286
22 0.7231428571428572
23 0.7235714285714285
24 0.7227857142857143
25 0.7234285714285714
26 0.7234285714285714
27 0.7234285714285714
28 0.7227142857142858
29 0.7233571428571428
30 0.7227857142857143
31 0.7233571428571428
32 0.7232142857142857
33 0.7231428571428572
34 0.7233571428571428
35 0.7235714285714285
36 0.7235
37 0.7235
38 0.7237142857142858
39 0.7260714285714286
40 0.7261428571428571
41 0.7260714285714286
42 0.7260714285714286
43 0.726
44 0.7260714285714286
45 0.7261428571428571
46 0.7261428571428571
47 0.7261428571428571
48 0.7261428571428571
49 0.7261428571428571
50 0.7261428571428571
51 0.7261428571428571
52 0.7261428571428571
53 0.7261428571428571
54 0.7236428571428571
55 0.7261428571428571
56 0.7261428571428571
57 0.7260714285714286
58 0.7261428571428571
59 0.7261428571428571
60 0.7255714285714285
61 0.7261428571428571
62 0.7261428571428571
63 0.7261428571428571
64 0.7261428571428571
65 0.7261428571428571
66 0.7261428571428571
67 0.7261428571428571
68 0.7261428571428571
69 0.7262142857142857
70 0.7261428571428571
71 0.7261428571428571
72 0.7261428571428571
73 0.7261428571428571
74 0.7261428571428571
75 0.7261428571428571
76 0.7261428571428571
77 0.7261428571428571
78 0.7261428571428571
79 0.7261428571428571
80 0.726
81 0.7261428571428571
82 0.726
83 0.7261428571428571
84 0.7255714285714285
85 0.7261428571428571
86 0.7256428571428571
87 0.7262142857142857
88 0.7262142857142857
89 0.7261428571428571
90 0.7261428571428571
91 0.7261428571428571
92 0.7261428571428571
93 0.7261428571428571
94 0.7262142857142857
95 0.7262142857142857
96 0.7262142857142857
97 0.7262142857142857
98 0.7261428571428571
99 0.7261428571428571
              precision    recall  f1-score   support

           0       0.70      0.78      0.74      6988
           1       0.76      0.67      0.71      7012

    accuracy                           0.73     14000
   macro avg       0.73      0.73      0.73     14000
weighted avg       0.73      0.73      0.73     14000

In [ ]:
model_knn = KNeighborsClassifier(n_neighbors=88, weights='distance')
model_knn.fit(X_train, y_train)

y_pred_knn = model_knn.predict(X_test)
print(classification_report(y_test, y_pred_knn))

              precision    recall  f1-score   support

           0       0.70      0.78      0.74      6988
           1       0.76      0.67      0.71      7012

    accuracy                           0.73     14000
   macro avg       0.73      0.73      0.73     14000
weighted avg       0.73      0.73      0.73     14000

In [ ]:
# Define the pipeline for the KNN
knn_pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("clf", KNeighborsClassifier(n_neighbors=88))
])

# Train the KNN model
knn_pipeline.fit(X_train, y_train)

def predict_cardio(user_input):
    user_df = pd.DataFrame(user_input, index=[0])
    prediction = knn_pipeline.predict(user_df)
    return 'Cardiovascular Disease' if prediction[0] == 1 else 'No Cardiovascular Disease'

def get_user_input():
    user_input = {
        #'age': int(input("Enter age (days since birth): ")),
        #'gender': int(input("Enter gender (1 for female, 2 for male): ")),
        #'height': float(input("Enter height (cm): ")),
        #'weight': float(input("Enter weight (kg): ")),
        'ap_hi': int(input("Enter systolic blood pressure (ap_hi): ")),
        #'ap_lo': int(input("Enter diastolic blood pressure (ap_lo): ")),
        'cholesterol': int(input("Enter cholesterol level (1: normal, 2: above normal, 3: well above normal): ")),
        'gluc': int(input("Enter glucose level (1: normal, 2: above normal, 3: well above normal): ")),
        'smoke': int(input("Do you smoke? (0: no, 1: yes): ")),
        'alco': int(input("Do you drink alcohol? (0: no, 1: yes): ")),
        'active': int(input("Are you physically active? (0: no, 1: yes): "))
    }
    return user_input

# Gather user input
user_input = get_user_input()

result = predict_cardio(user_input)
print("Prediction for the input values is:", result)

Enter systolic blood pressure (ap_hi): 110
Enter cholesterol level (1: normal, 2: above normal, 3: well above normal): 1
Enter glucose level (1: normal, 2: above normal, 3: well above normal): 1
Do you smoke? (0: no, 1: yes): 0
Do you drink alcohol? (0: no, 1: yes): 0
Are you physically active? (0: no, 1: yes): 1
Prediction for the input values is: No Cardiovascular Disease