<a href="https://colab.research.google.com/github/AliciaWang55/Machine-Learning-in-Predictive-Cardiology/blob/main/mlp_alicia_finalproject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.metrics import classification_report, accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler

from sklearn.neural_network import MLPClassifier
from sklearn.datasets import fetch_openml
from tensorflow.keras import layers, models

! gdown 1uHmHZdG4shgl3UwB1jtvkgmrQz9Zuwp8

Downloading...
From: https://drive.google.com/uc?id=1uHmHZdG4shgl3UwB1jtvkgmrQz9Zuwp8
To: /content/heart_data.csv
100% 3.35M/3.35M [00:00<00:00, 18.6MB/s]

In [ ]:
df = pd.read_csv('heart_data.csv')
df.head()

,index,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,0,18393,2,168,62.0,110,80,1,1,0,0,1,0
1,1,1,20228,1,156,85.0,140,90,3,1,0,0,1,1
2,2,2,18857,1,165,64.0,130,70,3,1,0,0,0,1
3,3,3,17623,2,169,82.0,150,100,1,1,0,0,1,1
4,4,4,17474,1,156,56.0,100,60,1,1,0,0,0,0

In [ ]:
# for i in range(len(df['active'])):
#   if df['active'][i] == 1:
#     df['active'][i] = 0
#   elif df['active'][i] == 0:
#     df['active'][i] = 1

df['active'] = 1-df['active']

df.head()

,index,id,age,gender,height,weight,ap_hi,ap_lo,cholesterol,gluc,smoke,alco,active,cardio
0,0,0,18393,2,168,62.0,110,80,1,1,0,0,0,0
1,1,1,20228,1,156,85.0,140,90,3,1,0,0,0,1
2,2,2,18857,1,165,64.0,130,70,3,1,0,0,1,1
3,3,3,17623,2,169,82.0,150,100,1,1,0,0,0,1
4,4,4,17474,1,156,56.0,100,60,1,1,0,0,1,0

In [ ]:
X = df[['age', 'gender', 'weight', 'ap_hi', 'cholesterol', 'gluc', 'smoke', 'alco', 'active']] # 73.7
y = df['cardio']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scaling the data
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

mlp = MLPClassifier(hidden_layer_sizes=(7,25,25,25,7), activation='relu', max_iter=500)
mlp.fit(X_train_scaled, y_train)

y_pred = mlp.predict(X_test_scaled)
acc = mlp.score(X_test_scaled, y_test)
print("Accuracy:", acc)
print("Confusion matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification report:\n", classification_report(y_test, y_pred))

Accuracy: 0.7372142857142857
Confusion matrix:
 [[5341 1647]
 [2032 4980]]
Classification report:
               precision    recall  f1-score   support

           0       0.72      0.76      0.74      6988
           1       0.75      0.71      0.73      7012

    accuracy                           0.74     14000
   macro avg       0.74      0.74      0.74     14000
weighted avg       0.74      0.74      0.74     14000